#*******************************************************************************
#*******************************************************************************
proc altera_cfg_header_gen {CFG_DIR} {
	#-----------------------------------
	set DEBUG_INFO 0

	#-----------------------------------
	set CFG_PARAMS_FILE ${CFG_DIR}/cfg_params.tcl

	#-----------------------------------
	set prjDefFile [open [set fileName "$CFG_DIR/cfg_params_generated.svh"] w];
	set guardName  [string toupper [set name "cfg_params_generated_svh"]];

	puts $prjDefFile [format "//--------------------------------------------------------------"];
	puts $prjDefFile [format "// This file is automatically generated. Do not edit this file"];
	puts $prjDefFile [format "//--------------------------------------------------------------"];
	puts $prjDefFile [format "`ifndef %s"  $guardName];
	puts $prjDefFile [format "`define %s\n"  $guardName];

	#-----------------------------------
	puts $prjDefFile [format "//--- automatically define section"];
	puts $prjDefFile [format "`define QUARTUS\n"];
	if {[file exists $CFG_PARAMS_FILE] == 1} {
		puts $prjDefFile [format "//--- user define section"];
		source $CFG_PARAMS_FILE
	}
	#-----------------------------------

	puts $prjDefFile [format "\n`endif //%s"  $guardName];

	close $prjDefFile;

	#-----------------------------------
	if {$DEBUG_INFO == 1} {
		puts "\[DEBUG\] \[altera_cfg_gen\]"
		puts " CFG_DIR:     $CFG_DIR"
	}
}

#*******************************************************************************
#*******************************************************************************
package require ::quartus::project

#-----------------------------------
set DEBUG_INFO 1

set sfxSV  *.sv
set sfxV   *.v
set sfxSDC *.sdc

#-----------------------------------
set SRC_DIR           [lindex $argv 0]
set OUT_CFG_DIR       [lindex $argv 1]
set PRJ_NAME          [lindex $argv 2]
set TARGET_FILE_NAME  [lindex $argv 3]
#-----------------------------------
set CFG_DIR [pwd]

#-----------------------------------
set srcFileListStart 4
set srcFileNum [expr $argc - $srcFileListStart]
set srcFileList [lrange $argv $srcFileListStart end]

#-----------------------------------

project_new [file normalize ${OUT_CFG_DIR}/${TARGET_FILE_NAME}]

#-----------------------------------
source ${CFG_DIR}/settings.tcl
source ${CFG_DIR}/signals.tcl
source ${CFG_DIR}/groups.tcl

#-----------------------------------
altera_cfg_header_gen $CFG_DIR

#-----------------------------------
set_global_assignment -name SEARCH_PATH  ${CFG_DIR}
set_global_assignment -name SEARCH_PATH  ${SRC_DIR}
#set_global_assignment -name HTML_REPORT_FILE ${TARGET_FILE_NAME}
set_global_assignment -name TEXT_FORMAT_REPORT_FILE ${TARGET_FILE_NAME}

#-----------------------------------

#--- SystemVerilog file list
set srcSV [lsearch -all -inline $srcFileList $sfxSV]
foreach src $srcSV {
	set_global_assignment -name SYSTEMVERILOG_FILE $src
} 

#--- Verilog file list
set srcV  [lsearch -all -inline $srcFileList $sfxV]
foreach src $srcV {
	set_global_assignment -name VERILOG_FILE $src
} 

#--- SDC file list
set srcSDC  [lsearch -all -inline $srcFileList $sfxSDC]
foreach src $srcSDC {
	set_global_assignment -name SDC_FILE ${CFG_DIR}/$src
} 

#-----------------------------------
export_assignments
project_close

#-----------------------------------
if {$DEBUG_INFO == 1} {
	puts "\[DEBUG\] \[altera_prj_gen\]"
	puts "SRC_DIR:          $SRC_DIR"
	puts "OUT_CFG_DIR:      $OUT_CFG_DIR"
	puts "PRJ_NAME:         $PRJ_NAME"
	puts "TARGET_FILE_NAME: $TARGET_FILE_NAME"
set QUARTUS_OUT_DIR [lindex $argv 4]
}
