#*******************************************************************************
#*******************************************************************************
proc cfg_header_gen {CFG_DIR BUILD_TOOL} {
	#-----------------------------------
	set DEBUG_INFO 0

	#-----------------------------------
	set CFG_PARAMS_FILE ${CFG_DIR}/cfg_params.tcl

	#-----------------------------------
	set prjDefFile [open [set fileName "$CFG_DIR/cfg_params_generated.svh"] w];
	set guardName  [string toupper [set name "cfg_params_generated_svh"]];

	puts $prjDefFile [format "//--------------------------------------------------------------"];
	puts $prjDefFile [format "// This file is automatically generated. Do not edit this file"];
	puts $prjDefFile [format "//--------------------------------------------------------------"];
	puts $prjDefFile [format "`ifndef %s"  $guardName];
	puts $prjDefFile [format "`define %s\n"  $guardName];

	#-----------------------------------
	puts $prjDefFile [format "//--- automatically define section"];
	puts $prjDefFile [format "`define $BUILD_TOOL\n"];
	if {[file exists $CFG_PARAMS_FILE] == 1} {
		puts $prjDefFile [format "//--- user define section"];
		source $CFG_PARAMS_FILE
	}
	#-----------------------------------

	puts $prjDefFile [format "\n`endif //%s"  $guardName];

	close $prjDefFile;

	#-----------------------------------
	if {$DEBUG_INFO == 1} {
		puts "\[DEBUG\] \[altera_cfg_gen\]"
		puts " CFG_DIR:     $CFG_DIR"
	}
}
